kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: custom-service-reader
rules:
  - apiGroups: ["sample.javaoperatorsdk"] # "" indicates the core API group
    resources: ["customservices"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: custom-service-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: slop-api-source
spec:
  resources:
    - apiVersion: "sample.javaoperatorsdk/v1"
      kind: CustomService
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: slop
    uri: /event
